In [5]:
import numpy as np, pandas as pd, math

def getDataFile():
    filename = "example.xls"
    return pd.read_excel(filename)

def improveDataFileForAccuracy(datafile):
    values = datafile.values
    m = np.size(values,0) 
    n = np.size(values,1)
    p = []
    for i in range (0,m):
        for j in range(0,n):
            if isinstance(values[i,j], basestring) or np.isnan(values[i,j]):
                p.append(i)
                break
    datafile = np.delete(values, p, axis = 0)
    datafile = datafile[:,41:51]
    return datafile
        
def getMeanOfColumn(index):
    rowscount = np.size(df, 0)
    sum = 0
    for i in range(0,rowscount):
        sum = df[i, index] + sum
    return sum/rowscount

def getDispersionOfColumn(index):
    mean = getMeanOfColumn(index)   
    sumOfSq = 0
    rowscount = np.size(df,0)
    for i in range(0, rowscount):
        sumOfSq = math.pow(df[i,index] - mean,2) + sumOfSq
    return sumOfSq/rowscount

def getDataFrame():
    datafile = getDataFile()
    datafile = improveDataFileForAccuracy(datafile)
    return datafile

def getStandardMatrix():
    rowscount = np.size(df,0)
    columnscount = np.size(df,1)
    standardMatrix = np.zeros((rowscount,columnscount))
    for i in range(0,columnscount):
        for j in range(0,rowscount):
            standardMatrix[j,i] = (df[j,i] - getMeanOfColumn(i))/math.sqrt(getDispersionOfColumn(i))
    return standardMatrix

def getCovMatrix():
    rowscount = np.size(df,0)
    columnscount = np.size(df,1)
    covMatrix = np.zeros((columnscount,columnscount))
    for i in range(0,columnscount):
        for j in range(0,columnscount):
            value = 0
            for k in range(0, rowscount):
                value = value + (df[k,i] - getMeanOfColumn(i))*(df[k,j] - getMeanOfColumn(j))
            covMatrix[i,j] = value/rowscount
    return covMatrix
    
def getCorrMatrix():
    rowscount = np.size(df,0)
    columnscount = np.size(df,1)
    corrMatrix = np.zeros((columnscount,columnscount))
    standardMatrix = getStandardMatrix()
    for i in range(0, columnscount):
        for j in range(0,columnscount):
            value = 0
            for k in range(0,rowscount):
                value = standardMatrix[k,i]*standardMatrix[k,j] + value
            corrMatrix[i,j] = value/rowscount
    return corrMatrix

def printMatrixOfAnalyzeHypothesisOfCorr():
    columnscount = np.size(df,1)
    corrMatrix = getCorrMatrix()
    matrixOfStatistics = np.zeros((columnscount, columnscount))
    for i in range(0, columnscount):
        for j in range(0, columnscount):
            r = corrMatrix[i,j]
            if i != j:
                t =  (r*math.sqrt(columnscount - 2))/math.sqrt(1 - math.pow(r,2))
                if abs(t) >= 2.228:
                    matrixOfStatistics[i,j] = True
                else: 
                    matrixOfStatistics[i,j] = False
    print matrixOfStatistics
    
def printMeans():
    p = []
    columnscount = np.size(df,1)
    print "Средние значения по столбцам: "
    for i in range(0, columnscount):
        print "%.2f" % (getMeanOfColumn(i)),
    print
    
def printDispersions():
    p = []
    columnscount = np.size(df,1)
    print "Значения дисперсий по столбцам: "
    for i in range(0,columnscount):
        print "%.2f" % (getDispersionOfColumn(i)),
    print

def printStandardMatrix():
    print "Стандартизованная матрица: "
    standardMatrix = getStandardMatrix()
    np.set_printoptions(precision = 3, suppress = True)
    print standardMatrix
    
def printCovMatrix():
    covMatrix = getCovMatrix()
    print "Ковариационная матрица: "
    np.set_printoptions(formatter={'float': '{:0.2f}'.format})
    print covMatrix
    
def printCorrMatrix():
    corrMatrix = getCorrMatrix()
    print "Корреляционная матрица: "
    np.set_printoptions(precision = 3, suppress = True)
    print corrMatrix
    
df = getDataFrame() 
#df = np.matrix([[1,3,4],[2,10,4],[3,6,7]])
printMeans()
printDispersions()
printStandardMatrix()
printCovMatrix()
printCorrMatrix()
printMatrixOfAnalyzeHypothesisOfCorr()

Средние значения по столбцам: 
19.92 13.58 22.44 9.63 66.24 1965.11 111.61 4498.41 74906.00 104.98
Значения дисперсий по столбцам: 
30.66 36.91 83.85 52.41 2228.93 2759483.61 15487.93 27104460.51 10441529412.82 127.49
Стандартизованная матрица: 
[[ 3.988  4.842  2.355  4.886 -0.429 -1.155 -0.511 -0.855 -0.733 -4.781]
 [-0.166  0.085  1.132 -0.694 -0.74  -0.431 -0.848 -0.288 -0.307  0.09 ]
 [ 0.917 -0.079 -1.096  0.383 -0.719 -0.859 -0.701 -0.599 -0.55   0.71 ]
 [ 0.701  0.316 -0.823 -0.211 -0.64  -0.85  -0.3   -0.667 -0.55   0.71 ]
 [-0.69  -0.919 -0.463 -0.073 -0.246  0.576  0.544 -0.278 -0.44   0.887]
 [-0.329 -0.573 -1.14   0.328 -0.92  -0.923 -0.792 -0.571 -0.573  1.153]
 [-0.148 -0.524 -0.823 -0.225 -0.066 -0.331  0.596 -0.308 -0.435 -0.087]
 [-0.943 -0.277 -0.157  0.342 -0.818 -0.43  -0.534 -0.717 -0.414  0.533]
 [-0.708  0.777 -1.446 -0.473 -1.03  -0.691 -0.841 -0.75  -0.629 -0.264]
 [ 0.827 -0.491 -0.812  0.038 -1.041 -1.08  -0.303 -0.702 -0.552  0.533]
 [-0.6    0.349 -0.375 -